--------------------------------------------------------
--  File created - Wednesday-October-30-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence DEMO_CUST_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TOLGAOOP"."DEMO_CUST_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DEMO_ORDER_ITEMS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TOLGAOOP"."DEMO_ORDER_ITEMS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DEMO_ORD_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TOLGAOOP"."DEMO_ORD_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 11 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DEMO_PROD_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TOLGAOOP"."DEMO_PROD_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DEMO_USERS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TOLGAOOP"."DEMO_USERS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "TOLGAOOP"."CLIENT" 
   (	"ID_CLIENT" NUMBER(*,0), 
	"FIRSTNAME" VARCHAR2(20 CHAR), 
	"LAASTNAME" VARCHAR2(20 CHAR), 
	"ADDRES" VARCHAR2(30 CHAR), 
	"PHONE" VARCHAR2(10 CHAR), 
	"AGE" NUMBER(*,0), 
	"REITING" NUMBER(*,0), 
	"HOTEL_ID_HOTEL" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table HOTEL
--------------------------------------------------------

  CREATE TABLE "TOLGAOOP"."HOTEL" 
   (	"ID_HOTEL" NUMBER(*,0), 
	"NAME" VARCHAR2(20 CHAR), 
	"ADDRESS" VARCHAR2(30 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table HOTELSERVICES
--------------------------------------------------------

  CREATE TABLE "TOLGAOOP"."HOTELSERVICES" 
   (	"ID_SERVICE" NUMBER(*,0), 
	"TYPESERVICE" VARCHAR2(30 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LOGIN
--------------------------------------------------------

  CREATE TABLE "TOLGAOOP"."LOGIN" 
   (	"ID_LOG" NUMBER(*,0), 
	"FNAME" VARCHAR2(20 CHAR), 
	"LNAME" VARCHAR2(20 CHAR), 
	"PASSWORD" VARCHAR2(10 CHAR), 
	"number" NUMBER(*,0), 
	"HOTEL_ID_HOTEL" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RECEPCIONIST
--------------------------------------------------------

  CREATE TABLE "TOLGAOOP"."RECEPCIONIST" 
   (	"ID_RECEP" NUMBER(*,0), 
	"NFNAME" VARCHAR2(20 CHAR), 
	"NLNAME" VARCHAR2(20 CHAR), 
	"NPASSWORD" VARCHAR2(20 CHAR), 
	"RESERVATION_ID_REZERVACION" NUMBER(*,0), 
	"HOTEL_ID_HOTEL" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RESERVATION
--------------------------------------------------------

  CREATE TABLE "TOLGAOOP"."RESERVATION" 
   (	"ID_REZERVACION" NUMBER(*,0), 
	"DATEBEGIN" DATE, 
	"DATEEND" DATE, 
	"CLIENT_ID_CLIENT" NUMBER(*,0), 
	"HOTELSERVICES_ID_SERVICE" NUMBER(*,0), 
	"TYPEPAKET_ID_TYPEPAKET" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ROOM
--------------------------------------------------------

  CREATE TABLE "TOLGAOOP"."ROOM" 
   (	"ID_ROOM" NUMBER(*,0), 
	"STATUS" CHAR(1 BYTE), 
	"ROOMNUMBER" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ROOMRESERVATION
--------------------------------------------------------

  CREATE TABLE "TOLGAOOP"."ROOMRESERVATION" 
   (	"RESERVATION_ID_REZERVACION" NUMBER(*,0), 
	"ROOM_ID_ROOM" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TYPEPAKET
--------------------------------------------------------

  CREATE TABLE "TOLGAOOP"."TYPEPAKET" 
   (	"ID_TYPEPAKET" NUMBER(*,0), 
	"TYPEPAKET" VARCHAR2(40 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into TOLGAOOP.CLIENT
SET DEFINE OFF;
REM INSERTING into TOLGAOOP.HOTEL
SET DEFINE OFF;
REM INSERTING into TOLGAOOP.HOTELSERVICES
SET DEFINE OFF;
REM INSERTING into TOLGAOOP.LOGIN
SET DEFINE OFF;
REM INSERTING into TOLGAOOP.RECEPCIONIST
SET DEFINE OFF;
REM INSERTING into TOLGAOOP.RESERVATION
SET DEFINE OFF;
REM INSERTING into TOLGAOOP.ROOM
SET DEFINE OFF;
REM INSERTING into TOLGAOOP.ROOMRESERVATION
SET DEFINE OFF;
REM INSERTING into TOLGAOOP.TYPEPAKET
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index CLIENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TOLGAOOP"."CLIENT_PK" ON "TOLGAOOP"."CLIENT" ("ID_CLIENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ROOM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TOLGAOOP"."ROOM_PK" ON "TOLGAOOP"."ROOM" ("ID_ROOM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index HOTEL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TOLGAOOP"."HOTEL_PK" ON "TOLGAOOP"."HOTEL" ("ID_HOTEL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index HOTELSERVICES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TOLGAOOP"."HOTELSERVICES_PK" ON "TOLGAOOP"."HOTELSERVICES" ("ID_SERVICE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RECEPCIONIST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TOLGAOOP"."RECEPCIONIST_PK" ON "TOLGAOOP"."RECEPCIONIST" ("ID_RECEP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RESERVATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TOLGAOOP"."RESERVATION_PK" ON "TOLGAOOP"."RESERVATION" ("ID_REZERVACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TYPEPAKET_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TOLGAOOP"."TYPEPAKET_PK" ON "TOLGAOOP"."TYPEPAKET" ("ID_TYPEPAKET") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index LOGIN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TOLGAOOP"."LOGIN_PK" ON "TOLGAOOP"."LOGIN" ("ID_LOG") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Function CUSTOM_AUTH
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "TOLGAOOP"."CUSTOM_AUTH" (p_username in VARCHAR2, p_password in VARCHAR2)
return BOOLEAN
is
  l_password varchar2(4000);
  l_stored_password varchar2(4000);
  l_expires_on date;
  l_count number;
begin
-- First, check to see if the user is in the user table
select count(*) into l_count from demo_users where user_name = p_username;
if l_count > 0 then
  -- First, we fetch the stored hashed password & expire date
  select password, expires_on into l_stored_password, l_expires_on
   from demo_users where user_name = p_username;

  -- Next, we check to see if the user's account is expired
  -- If it is, return FALSE
  if l_expires_on > sysdate or l_expires_on is null then

    -- If the account is not expired, we have to apply the custom hash
    -- function to the password
    l_password := custom_hash(p_username, p_password);

    -- Finally, we compare them to see if they are the same and return
    -- either TRUE or FALSE
    if l_password = l_stored_password then
      return true;
    else
      return false;
    end if;
  else
    return false;
  end if;
else
  -- The username provided is not in the DEMO_USERS table
  return false;
end if;
end;

/
--------------------------------------------------------
--  DDL for Function CUSTOM_HASH
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "TOLGAOOP"."CUSTOM_HASH" (p_username in varchar2, p_password in varchar2)
return varchar2
is
  l_password varchar2(4000);
  l_salt varchar2(4000) := 'BH0Y11H755RPHJ4E4WGW16VPQ4XCJS';
begin

-- This function should be wrapped, as the hash algorhythm is exposed here.
-- You can change the value of l_salt or the method of which to call the
-- DBMS_OBFUSCATOIN toolkit, but you much reset all of your passwords
-- if you choose to do this.

l_password := utl_raw.cast_to_raw(dbms_obfuscation_toolkit.md5
  (input_string => p_password || substr(l_salt,10,13) || p_username ||
    substr(l_salt, 4,10)));
return l_password;
end;

/
--------------------------------------------------------
--  Constraints for Table RESERVATION
--------------------------------------------------------

  ALTER TABLE "TOLGAOOP"."RESERVATION" ADD CONSTRAINT "RESERVATION_PK" PRIMARY KEY ("ID_REZERVACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TOLGAOOP"."RESERVATION" MODIFY ("TYPEPAKET_ID_TYPEPAKET" NOT NULL ENABLE);
  ALTER TABLE "TOLGAOOP"."RESERVATION" MODIFY ("HOTELSERVICES_ID_SERVICE" NOT NULL ENABLE);
  ALTER TABLE "TOLGAOOP"."RESERVATION" MODIFY ("CLIENT_ID_CLIENT" NOT NULL ENABLE);
  ALTER TABLE "TOLGAOOP"."RESERVATION" MODIFY ("ID_REZERVACION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RECEPCIONIST
--------------------------------------------------------

  ALTER TABLE "TOLGAOOP"."RECEPCIONIST" ADD CONSTRAINT "RECEPCIONIST_PK" PRIMARY KEY ("ID_RECEP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TOLGAOOP"."RECEPCIONIST" MODIFY ("HOTEL_ID_HOTEL" NOT NULL ENABLE);
  ALTER TABLE "TOLGAOOP"."RECEPCIONIST" MODIFY ("RESERVATION_ID_REZERVACION" NOT NULL ENABLE);
  ALTER TABLE "TOLGAOOP"."RECEPCIONIST" MODIFY ("ID_RECEP" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ROOMRESERVATION
--------------------------------------------------------

  ALTER TABLE "TOLGAOOP"."ROOMRESERVATION" MODIFY ("ROOM_ID_ROOM" NOT NULL ENABLE);
  ALTER TABLE "TOLGAOOP"."ROOMRESERVATION" MODIFY ("RESERVATION_ID_REZERVACION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HOTEL
--------------------------------------------------------

  ALTER TABLE "TOLGAOOP"."HOTEL" ADD CONSTRAINT "HOTEL_PK" PRIMARY KEY ("ID_HOTEL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TOLGAOOP"."HOTEL" MODIFY ("ID_HOTEL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "TOLGAOOP"."CLIENT" ADD CONSTRAINT "CLIENT_PK" PRIMARY KEY ("ID_CLIENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TOLGAOOP"."CLIENT" MODIFY ("HOTEL_ID_HOTEL" NOT NULL ENABLE);
  ALTER TABLE "TOLGAOOP"."CLIENT" MODIFY ("ID_CLIENT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HOTELSERVICES
--------------------------------------------------------

  ALTER TABLE "TOLGAOOP"."HOTELSERVICES" ADD CONSTRAINT "HOTELSERVICES_PK" PRIMARY KEY ("ID_SERVICE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TOLGAOOP"."HOTELSERVICES" MODIFY ("ID_SERVICE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ROOM
--------------------------------------------------------

  ALTER TABLE "TOLGAOOP"."ROOM" ADD CONSTRAINT "ROOM_PK" PRIMARY KEY ("ID_ROOM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TOLGAOOP"."ROOM" MODIFY ("ID_ROOM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LOGIN
--------------------------------------------------------

  ALTER TABLE "TOLGAOOP"."LOGIN" ADD CONSTRAINT "LOGIN_PK" PRIMARY KEY ("ID_LOG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TOLGAOOP"."LOGIN" MODIFY ("HOTEL_ID_HOTEL" NOT NULL ENABLE);
  ALTER TABLE "TOLGAOOP"."LOGIN" MODIFY ("ID_LOG" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TYPEPAKET
--------------------------------------------------------

  ALTER TABLE "TOLGAOOP"."TYPEPAKET" ADD CONSTRAINT "TYPEPAKET_PK" PRIMARY KEY ("ID_TYPEPAKET")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TOLGAOOP"."TYPEPAKET" MODIFY ("ID_TYPEPAKET" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "TOLGAOOP"."CLIENT" ADD CONSTRAINT "CLIENT_HOTEL_FK" FOREIGN KEY ("HOTEL_ID_HOTEL")
	  REFERENCES "TOLGAOOP"."HOTEL" ("ID_HOTEL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LOGIN
--------------------------------------------------------

  ALTER TABLE "TOLGAOOP"."LOGIN" ADD CONSTRAINT "LOGIN_HOTEL_FK" FOREIGN KEY ("HOTEL_ID_HOTEL")
	  REFERENCES "TOLGAOOP"."HOTEL" ("ID_HOTEL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RECEPCIONIST
--------------------------------------------------------

  ALTER TABLE "TOLGAOOP"."RECEPCIONIST" ADD CONSTRAINT "RECEPCIONIST_HOTEL_FK" FOREIGN KEY ("HOTEL_ID_HOTEL")
	  REFERENCES "TOLGAOOP"."HOTEL" ("ID_HOTEL") ENABLE;
  ALTER TABLE "TOLGAOOP"."RECEPCIONIST" ADD CONSTRAINT "RECEPCIONIST_RESERVATION_FK" FOREIGN KEY ("RESERVATION_ID_REZERVACION")
	  REFERENCES "TOLGAOOP"."RESERVATION" ("ID_REZERVACION") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESERVATION
--------------------------------------------------------

  ALTER TABLE "TOLGAOOP"."RESERVATION" ADD CONSTRAINT "RESERVATION_CLIENT_FK" FOREIGN KEY ("CLIENT_ID_CLIENT")
	  REFERENCES "TOLGAOOP"."CLIENT" ("ID_CLIENT") ENABLE;
  ALTER TABLE "TOLGAOOP"."RESERVATION" ADD CONSTRAINT "RESERVATION_HOTELSERVICES_FK" FOREIGN KEY ("HOTELSERVICES_ID_SERVICE")
	  REFERENCES "TOLGAOOP"."HOTELSERVICES" ("ID_SERVICE") ENABLE;
  ALTER TABLE "TOLGAOOP"."RESERVATION" ADD CONSTRAINT "RESERVATION_TYPEPAKET_FK" FOREIGN KEY ("TYPEPAKET_ID_TYPEPAKET")
	  REFERENCES "TOLGAOOP"."TYPEPAKET" ("ID_TYPEPAKET") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ROOMRESERVATION
--------------------------------------------------------

  ALTER TABLE "TOLGAOOP"."ROOMRESERVATION" ADD CONSTRAINT "ROOMRESERVATION_RESERVATION_FK" FOREIGN KEY ("RESERVATION_ID_REZERVACION")
	  REFERENCES "TOLGAOOP"."RESERVATION" ("ID_REZERVACION") ENABLE;
  ALTER TABLE "TOLGAOOP"."ROOMRESERVATION" ADD CONSTRAINT "ROOMRESERVATION_ROOM_FK" FOREIGN KEY ("ROOM_ID_ROOM")
	  REFERENCES "TOLGAOOP"."ROOM" ("ID_ROOM") ENABLE;
